api:
  entities:
    Training\Bundle\UserNamingBundle\Entity\UserNamingType:
      filters:
        fields:
          title:
            exclude: false
      sorters:
        fields:
          title:
            exclude: false
      fields:
        example:
          data_type: string
          meta_property: true