imports:
    - { resource: 'workflow/includes/attributes.yml' }
    - { resource: 'workflow/training_flow_checkout/steps.yml' }
    - { resource: 'workflow/includes/base_transitions.yml' }
    - { resource: 'workflow/includes/base_transition_definitions.yml' }
    - { resource: 'workflow/training_flow_checkout/transitions.yml' }
    - { resource: 'workflow/training_flow_checkout/transition_definitions.yml' }

workflows:
    training_flow_checkout:
        entity: Oro\Bundle\CheckoutBundle\Entity\Checkout
        entity_attribute: checkout
        steps_display_ordered: true

        defaults:
            active: false

        applications: ['commerce']

        variable_definitions:
            variables:
                test_email_pattern:
                    type: 'string'
                    value: '@(test|yopmail)\.com$'
                    options:
                        form_options:
                            constraints:
                                NotBlank: ~
                            tooltip: true

        exclusive_active_groups:
            - b2b_checkout_flow
        exclusive_record_groups:
            - b2b_checkout_flow

        priority: 200
