services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Training\Bundle\UserNamingBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Repository,Tests,Migrations}'

  Training\Bundle\UserNamingBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]

  Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator:
    decorates: oro_locale.entity_name_provider
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator.inner'
    tags:
      - { name: oro_entity.name_provider, priority: -60 }

  Training\Bundle\UserNamingBundle\EventListener\UserViewNamingListener:
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }
