services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Training\Bundle\UserNamingBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Repository,Tests,Migrations}'

  Training\Bundle\UserNamingBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]

  Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator:
    decorates: oro_locale.entity_name_provider
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator.inner'
    tags:
      - { name: oro_entity.name_provider, priority: -60 }

  Training\Bundle\UserNamingBundle\EventListener\UserViewNamingListener:
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }

  Training\Bundle\UserNamingBundle\EventListener\UserNamingListener:
    tags:
      - name: 'doctrine.orm.entity_listener'
        event: 'postPersist'
        entity: \Training\Bundle\UserNamingBundle\Entity\UserNamingType
      - name: 'doctrine.orm.entity_listener'
        event: 'preUpdate'
        entity: \Training\Bundle\UserNamingBundle\Entity\UserNamingType

  Training\Bundle\UserNamingBundle\Async\NamingExampleGeneratorProcessor:
    tags:
      - { name: 'oro_message_queue.client.message_processor' }